spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27019/loans?authSource=admin
      database: loans
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
        port: 35731
springdoc:
  swagger-ui:
    path: /api-docs

server:
  port: 8082

ms:
  course:
    url: http://localhost:8080/api/courses
  computer:
    url: http://localhost:8081/api/computers