spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/loans?authSource=admin
      database: loans
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
        port: 35731
springdoc:
  swagger-ui:
    path: /api/loans/docs
  api-docs:
      path: /api/loans/docs

server:
  port: 8082

ms:
  course:
    url: http://localhost:8080/api/courses
  student:
    url: http://localhost:8080/api/students
  computer:
    url: http://localhost:8081/api/computers

management:
  endpoints:
    jmx:
      exposure:
        include: 'health,info'
    web:
      base-path: '/api/loans/status'
      path-mapping:
        health: /health