spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@admiralis-db:27017/loans?authSource=admin
      database: loans
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
        port: 35731
springdoc:
  swagger-ui:
    path: /api-docs

server:
  port: 80

ms:
  course:
    url: http://ms-courses/api/courses
  student:
    url: http://ms-courses/api/students
  computer:
    url: http://ms-computers/api/computers
