spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@admiralis-db:27017/loans?authSource=admin
      database: loans
springdoc:
  swagger-ui:
    path: /api/loans/docs
  api-docs:
    path: /api/loans/docs

server:
  port: 80

ms:
  course:
    url: http://ms-course/api/courses
  student:
    url: http://ms-course/api/students
  computer:
    url: http://ms-computer/api/computers

management:
  endpoints:
    jmx:
      exposure:
        include: 'health,info'
    web:
      base-path: '/api/loans/status'
      path-mapping:
        health: /health
      cors:
        allowed-origins: '*'
        allowed-methods: GET,POST,PUT,DELETE